name = "SilMay"
author = "Silmar"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d69577d9ff38cecec962fea11ddac6cf27cd544e419f35922d13d1c1d54547ca"

[versions]
fabric = "0.17.2"
minecraft = "1.21"
