name = "SilMay"
author = "Silmar"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e11ce5853025a6ea84d961e389bd0bfc195b03a02d1fc0046a7b6d1ced635063"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
