name = "SilMay"
author = "Silmar"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d718d314c431e6d6bb5b40620aef3aff20ac733d506e0c7ed9d27189aa016cd"

[versions]
fabric = "0.17.2"
minecraft = "1.21"
