name = "SilMay"
author = "Silmar"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0db093fdcd01fdee2aed7f7da336b52d53432a045b688f73cad4c20c413ec8d"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
