name = "Aicalica"
author = "Silmar"
version = "2.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f38f0bce688a4ef5b9d10b9418b7fe642e6691d16c75bef67efc53979e070e8c"

[versions]
fabric = "0.17.2"
minecraft = "1.21"
