name = "Aicalica"
author = "Silmar"
version = "2.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ed7052a8ed96e706b1b1e29f5ccacd270f4bd87b410e2286588817adfbdf9f7"

[versions]
fabric = "0.17.2"
minecraft = "1.21"
