name = "Aicalica"
author = "Silmar"
version = "2.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea576acad61d6193b6b3a1611cac765646fdeee6972a4fd805ea9b64fba54bbe"

[versions]
fabric = "0.17.2"
minecraft = "1.21"
